export const BEKRAFTA_SUCCES = 'BEKRAFTA_SUCCES';

export const BEKRAFTA_FAILED = 'BEKRAFTA_FAILED';

export const MINGLA_STATE = 'MINGLA_STATE';

export const WORKLIST_FILLED = 'WORKLIST_FILLED';

export const WORKLIST_INITIAL_STATE = 'WORKLIST_INITIAL_STATE;';

export const CHECKVERB = 'CHECKVERB';

export const SVARVERB = 'SVARVERB';

export const EMPTY_TESTLIST = 'EMPTY_TESTLIST';

export const FILLED_TESTLIST = 'FILLED_TESTLIST';